rmdir /s /q final
rmdir /s /q comics_to_rename
rm todo.txt
rm log.txt
mkdir comics_to_rename
echo.>comics_to_rename/"Adventure Time 006 (4 covers) (2012) (Digital) (D-Rek-Empire).cbr"
echo.>comics_to_rename/"Ame-Comi V Supergirl 03 (of 03) (2012) (Digital) (Nahga-Empire).cbr"
echo.>comics_to_rename/"American Vampire 030 (2012) (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"American Vampire 030 (2012) (c2c) (theFragile-Minutemen-DCP).cbr"
echo.>comics_to_rename/"American Vampire 030 (2012) (noAds) (theFragile-Minutemen-DCP).cbr"
echo.>comics_to_rename/"Aquaman 012 (3 Covers) (2012) (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"Batman - Arkham Unhinged 041 (2012) (Digital) (Nahga-Empire).cbr"
echo.>comics_to_rename/"Before Watchmen - Minutemen 03 (of 06) (2012) (Minutemen-Resin).cbr"
echo.>comics_to_rename/"Burn Notice - First Contact v3 c12 (2012) (digital).cbr"
echo.>comics_to_rename/"Critter V2 3(c2c)(2012)(Re-em-DCP).cbr"
echo.>comics_to_rename/"Critter V2 3(c2c)(2012)(Re-em-DCP-HD).cbr"
echo.>comics_to_rename/"Crossed - Wish You Were Here v1 c19 (2012) (digital).cbr"
echo.>comics_to_rename/"Debris 02 (2012) (Tarutaru-DCP).cbr"
echo.>comics_to_rename/"Debris 02 (2012) (Tarutaru-DCP-HD).cbr"
echo.>comics_to_rename/"Detective Comics Annual 001 (2012) (digital-TheGroup).cbr"
echo.>comics_to_rename/"Diablo 05 (of 05) (2012) (digital-Empire).cbz"
echo.>comics_to_rename/"Dominique Laveau Voodoo Child 006 (2012) (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"FF 21 (2012) (Minutemen-DTs).cbz"
echo.>comics_to_rename/"Franklin Goes To School 1(c2c)(2012)(Re-em-DCP).cbr"
echo.>comics_to_rename/"Franklin Goes To School 1(c2c)(2012)(Re-em-DCP-HD).cbr"
echo.>comics_to_rename/"G-Fan 067(c2c)(Daikaiju)(2004)(YZ1).cbr"
echo.>comics_to_rename/"Godzilla 4(c2c)(3 covers)(2012)(Re-em-DCP).cbr"
echo.>comics_to_rename/"Green Hornet 027 (2012) (2 covers) (Digital) (Fawkes-Empire).cbr"
echo.>comics_to_rename/"Green Lantern Annual 01 (2012) (Digital) (Nahga-Empire).cbr"
echo.>comics_to_rename/"Grim Leaper 04 (of 04) (2012) (Digital) (Nahga-Empire).cbr"
echo.>comics_to_rename/"Hercules - The Thracian Wars 01 (of 05) (2008) (2 covers) (digital) (Minutemen-PhD).cbr"
echo.>comics_to_rename/"Higher Earth 004 (2012) (6 covers) (Digital) (Fawkes-Empire).cbr"
echo.>comics_to_rename/"Justice League 012 (2012) (4 covers) (digital-TheGroup).cbr"
echo.>comics_to_rename/"Justice League International Annual 001 (2012) (digital-TheGroup).cbr"
echo.>comics_to_rename/"Last Dragon 2(c2c)(2012)(Re-em-DCP).cbr"
echo.>comics_to_rename/"Last Dragon 2(c2c)(2012)(Re-em-DCP-HD).cbr"
echo.>comics_to_rename/"Legends of The Dark Knight 013 (2012) (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"Locke & Key - Grindhouse (c2c) (theProletariat-DCP).cbr"
echo.>comics_to_rename/"Lord of the Jungle 007 (2012) (2 covers) (Digital) (Fawkes-Empire).cbr"
echo.>comics_to_rename/"Mass Effect - Homeworlds 04 (2012) (2 Covers) (Tarutaru-DCP).cbr"
echo.>comics_to_rename/"Mass Effect - Homeworlds 04 (2012) (2 Covers) (Tarutaru-DCP-HD).cbr"
echo.>comics_to_rename/"Masters of the Universe 005 (2012) (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"Mudman 005 (2012) (Digital) (Fawkes-Empire).cbr"
echo.>comics_to_rename/"National Comics- Looker 001 (2012) (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"Phantom Lady and Doll Man 01 (of 04) (2012) (Digital) (Nahga-Empire).cbr"
echo.>comics_to_rename/"Planet of the Apes 13 (2012) (2 covers - c2c - 2048px) (theRevolutionaries-DCP-HD).cbr"
echo.>comics_to_rename/"Planet of the Apes 13 (2012) (2 covers - c2c) (theRevolutionaries-DCP).cbr"
echo.>comics_to_rename/"Powers v3 11 (2012) (c2c) (theProletariat-DCP).cbr"
echo.>comics_to_rename/"Powers v3 11 (2012) (noAds) (theProletariat-DCP).cbr"
echo.>comics_to_rename/"Prophecy 3(c2c)(2 covers)(2012)(Re-em-DCP).cbr"
echo.>comics_to_rename/"Prophecy 3(c2c)(2 covers)(2012)(Re-em-DCP-HD).cbr"
echo.>comics_to_rename/"Prophet 028 (2012) (digital-Empire).cbz"
echo.>comics_to_rename/"Red Sonja 68(c2c)(2 covers)(2012)(Re-em-DCP).cbr"
echo.>comics_to_rename/"Red Sonja 68(c2c)(2 covers)(2012)(Re-em-DCP-HD).cbr"
echo.>comics_to_rename/"Rue Morgue 126 (2012) (Digital) (Hexadecimal-Empire).cbr"
echo.>comics_to_rename/"Smallville Season 11 015 (2012) (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"Spider-Man Daily Strip 2012-08 (webrip by Lusiphur-DCP).cbr"
echo.>comics_to_rename/"Star Trek TNG Doctor Who Assimilation 4(c2c)(3 covers)(2012)(Re-em-DCP).cbr"
echo.>comics_to_rename/"Star Trek TNG Doctor Who Assimilation 4(c2c)(3 covers)(2012)(Re-em-DCP-HD).cbr"
echo.>comics_to_rename/"Star Wars - Darth Maul - Death Sentence 02 (2012) (c2c) (GreenGiant-DCP).cbr"
echo.>comics_to_rename/"Star Wars - Darth Maul - Death Sentence 02 (2012) (noads) (GreenGiant-DCP).cbr"
echo.>comics_to_rename/"Star Wars - Darth Maul - Death Sentence 02 (of 04) (2012) (Digital) (Fawkes-Empire).cbr"
echo.>comics_to_rename/"Superman Annual 01 (2012) (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"Superman Family Adventures 004 (2012) (digital-Empire).cbz"
echo.>comics_to_rename/"The Amazing Spider-Man 692 (2012) (6 covers - 2048px) (MegaProl-Minutemen-DCP-HD).cbr"
echo.>comics_to_rename/"The Amazing Spider-Man 692 (2012) (6 covers - c2c) (MegaProl-Minutemen-DCP).cbr"
echo.>comics_to_rename/"The Amazing Spider-Man 692 (2012) (6 covers) (MegaProl-Minutemen-DCP).cbr"
echo.>comics_to_rename/"The Flash Annual 001 (2012) (digital-TheGroup).cbr"
echo.>comics_to_rename/"The Goon 041 (2012) (Digital) (Fawkes-Empire).cbr"
echo.>comics_to_rename/"The Walking Dead 97 (2012) (2nd Printing Variant) (Cover ONLY) (ScanDog & ArtNet-DCP).cbz"
echo.>comics_to_rename/"The Walking Dead 97-99 (2012) (2nd Printing Variant Covers Poster Join) (Covers ONLY) (ScanDog & ArtNet-DCP).cbz"
echo.>comics_to_rename/"The Walking Dead 99 (2012) (2nd Printing Variant) (Cover ONLY) (ScanDog & ArtNet-DCP).cbz"
echo.>comics_to_rename/"Transformers Fall Of Cybertron 2 of 6 (2012) by Nook.cbr"
echo.>comics_to_rename/"Trio 004 (2012) (digital-TheGroup).cbr"
echo.>comics_to_rename/"Trio 4(c2c)(2012)(Re-em-DCP-HD).cbr"
echo.>comics_to_rename/"Ultimate Comics X-Men 015 (2012) (2048px) (theProletariat-DCP-HD).cbr"
echo.>comics_to_rename/"Ultimate Comics X-Men 015 (2012) (theProletariat-DCP).cbr"
echo.>comics_to_rename/"Uncanny X-Force 30 (2012) (Minutemen-DTs).cbz"
echo.>comics_to_rename/"Untold Tales of Punisher Max 003 (2012) (GreenGiant-DCP).cbr"
echo.>comics_to_rename/"Warlord of Mars - Dejah Thoris 014 (2012) (2 covers) (Digital) (Fawkes-Empire).cbr"
echo.>comics_to_rename/"Witchblade - Demon Reborn 02 (2012) (2 Covers) (Tarutaru-DCP).cbr"
echo.>comics_to_rename/"Witchblade - Demon Reborn 02 (2012) (2 Covers) (Tarutaru-DCP-HD).cbr"
echo.>comics_to_rename/"Witchblade 159 (2012) (2 Covers) (Tarutaru-DCP).cbr"
echo.>comics_to_rename/"Witchblade 159 (2012) (2 Covers) (Tarutaru-DCP-HD).cbr"
echo.>comics_to_rename/"Wrapped In Plastic 75(c2c)(Win-Mill Productions)(2005)(YZ1).cbr"
echo.>comics_to_rename/"X-O Manowar 004 (2012) (Digital) (Nahga-Empire).cbr"
echo.>comics_to_rename/"Young Justice 019 (2012) (digital-TheGroup).cbr"
echo.>comics_to_rename/"Action Comics 08 2012 Minutemen-DTs.cbz"
echo.>comics_to_rename/"Action Comics 08 2012 Minutemen-DTs.cbz"
echo.>comics_to_rename/"Age of Apocalypse 002 (2012) (digital-TheGroup).cbr"
echo.>comics_to_rename/"Age of Apocalypse 002 (2012) (digital-TheGroup).cbz"
echo.>comics_to_rename/"Amazing Spider-Man 683 (2012) (digital-TheGroup).cbr"
echo.>comics_to_rename/"Amazing Spider-Man 683 (2012) (digital-TheGroup).cbz"
echo.>comics_to_rename/"Animal Man 008 (2012) (RiZZ3N-Empire).cbr"
echo.>comics_to_rename/"Animal Man 008 (2012) (RiZZ3N-Empire).cbz"
echo.>comics_to_rename/"Avengers Academy 028 (2012) (digital-TheGroup).cbr"
echo.>comics_to_rename/"Avengers Academy 028 (2012) (digital-TheGroup).cbz"
echo.>comics_to_rename/"Avengers Vs X-Men 01 (2012) (1280px 100Pages)(Digital+) (Zone-Empire).cbr"
echo.>comics_to_rename/"Batwing 08 2012 Minutemen-DTs.cbz"
echo.>comics_to_rename/"Batwing 08 2012 Minutemen-DTs.cbz"
echo.>comics_to_rename/"Batwing 08 (2012) (1440px) (WebRip) (Shining Knight-SCC-DCP).cbz"
echo.>comics_to_rename/"Daredevil 10.1 (2012) (Digital) (Zone-Empire).cbz"
echo.>comics_to_rename/"Detective Comics 008 (2012) (3 covers) (digital-TheGroup).cbz"
echo.>comics_to_rename/"Fanboys vs. Zombies 001 (2012) (8 covers) (digital-Empire).cbz"
echo.>comics_to_rename/"Green Arrow 008 (2012) (digital-TheGroup).cbz"
echo.>comics_to_rename/"Justice League International 008 (2012) (digital-TheGroup).cbz"
echo.>comics_to_rename/"New Mutants 040 (2012) (digital-TheGroup).cbz"
echo.>comics_to_rename/"Night Force 02 of 07 2012 digital Empire .cbz"
echo.>comics_to_rename/"Stormwatch 008 (2012) (2 covers) (digital-Empire).cbz"
echo.>comics_to_rename/"Swamp Thing 008 (2012) (2 covers)(RiZZ3N-Empire).cbz"
echo.>comics_to_rename/"The Boys 65 2012 Minutemen DTs.cbz"
echo.>comics_to_rename/"Ultimate_Comics_Spider_Man_009_2012__Digital__Zone_Empire_.cbz"
echo.>comics_to_rename/"Venom 015 (2012) (digital-Empire).cbz"
echo.>comics_to_rename/"Wolverine and the X-Men - Alpha & Omega 04 (of 05) (2012) (Megan-Empire).cbz"
echo.>comics_to_rename/"Wolverine and the X-Men 008 (2012) (Megan-Empire).cbz"
echo.>comics_to_rename/"(ABS) Terry Moore's How To Draw Beautiful.cbz"
echo.>comics_to_rename/"(ACH) Sonic The Hedgehog 235.cbr"
echo.>comics_to_rename/"(AVA) Crossed - Wish You Were Here v1 03 (Digital Only).cbr"
echo.>comics_to_rename/"(AVK) Glamourpuss 24 (c2c).cbr"
echo.>comics_to_rename/"(BDI) The Legend Of Oz - The Wicked West 03.cbr"
echo.>comics_to_rename/"(BOM) Incorruptible 28 (2c).cbz"
echo.>comics_to_rename/"(BOM) Supurbia 02.cbr"
echo.>comics_to_rename/"(DRK) Criminal Macabre - Die Die My Darling 01.cbr"
echo.>comics_to_rename/"(DYN) Dejah Thoris And The White Apes Of Mars 01 (2c).cbr"
echo.>comics_to_rename/"(DYN) Jennifer Blood 11 (2c).cbr"
echo.>comics_to_rename/"(DYN) Kirby Genesis 06 (2c).cbr"
echo.>comics_to_rename/"(DYN) Queen Sonja 28 (c2c)(c2c).cbr"
echo.>comics_to_rename/"(DYN) Voltron - Year One 01 (2c).cbr"
echo.>comics_to_rename/"(DYN) Witchblade - Red Sonja 02.cbr"
echo.>comics_to_rename/"(IDW) 30 Days Of Night 06.cbr"
echo.>comics_to_rename/"(IMG) Chew 25.cbr"
echo.>comics_to_rename/"(IMG) Danger Club 01.cbr"
echo.>comics_to_rename/"(IMG) Fatale 04 (c2c).cbz"
echo.>comics_to_rename/"(IMG) Hell Yeah 02.cbr"
echo.>comics_to_rename/"(IMG) Invincible 90.cbz"
echo.>comics_to_rename/"(IMG) Mudman 03.cbr"
echo.>comics_to_rename/"(IMG) Savage Dragon 179 (c2c).cbr"
echo.>comics_to_rename/"(IMG) Skullkickers 13.cbr"
echo.>comics_to_rename/"(IMG) Supreme 63.cbr"
echo.>comics_to_rename/"(IMG) Whispers 02.cbz"
echo.>comics_to_rename/"(MST) Honey West 05 (c2c).cbr"
echo.>comics_to_rename/"(MST) Kolchak - Night Stalker Files 03 (2c)(c2c).cbr"
echo.>comics_to_rename/"(MST) Zombies vs Cheerleaders 06 (c2c).cbr"
echo.>comics_to_rename/"(TIT) Lenore v2 05 (2c)(c2c).cbr"
echo.>comics_to_rename/"(ZEN) Grimm Fairy Tales - 2012 April Fools Edition (c2c).cbr"
echo.>comics_to_rename/"(ZEN) Grimm Fairy Tales - The Library 05 (2c)(c2c).cbr"
echo.>comics_to_rename/"(ZEN) Grimm Fairy Tales 71 (2c)(c2c).cbr"
echo.>comics_to_rename/"Avengers vs X Men Infinite 01 (Digital Only).cbr"
echo.>comics_to_rename/"Brilliant 03.cbz"
echo.>comics_to_rename/"Casanova - Avaritia 03 (c2c).cbz"
echo.>comics_to_rename/"Disney Pixar Toy Story 02.cbr"
echo.>comics_to_rename/"Fairest 02.cbr"
echo.>comics_to_rename/"Fear Itself The Fearless 12.cbr"
echo.>comics_to_rename/"Harley Davidson Avengers 01 (Promo).cbr"
echo.>comics_to_rename/"Hawk & Dove 08.cbr"
echo.>comics_to_rename/"Hulk 50.cbr"
echo.>comics_to_rename/"I, Zombie 24.cbr"
echo.>comics_to_rename/"Justice League Beyond 05 (Digital Only).cbr"
echo.>comics_to_rename/"Men Of War 08.cbr"
echo.>comics_to_rename/"O.M.A.C. 08.cbr"
echo.>comics_to_rename/"Red Lanterns 08 (c2c).cbr"
echo.>comics_to_rename/"Static Shock 08.cbz"
echo.>comics_to_rename/"Sweet Tooth 32.cbz"
echo.>comics_to_rename/"Thunderbolts 172.cbr"
echo.>comics_to_rename/"Wolverine And The X Men - Alpha Omega 04.cbr"
echo.>comics_to_rename/"X-Club 05.cbz"
echo.>comics_to_rename/"Cixi of Troy #1 - The Secret of Cixi (2010) (Dragonz-Alice).cbz"
echo.>comics_to_rename/"03-07-12 (IDW) True Blood - French Quarter 06 (4c).cbr"
echo.>comics_to_rename/"03-21-12 Justice League Beyond 04 (Digital Only).cbr"
echo.>comics_to_rename/"(DYN) Lone Ranger 04 (c2c).cbr"
echo.>comics_to_rename/"Avengers vs X-Men 01 (9c).cbr"
echo.>comics_to_rename/"09-21-11 (DYN) Green Hornet 18.cbr"
echo.>comics_to_rename/"09-28-11 (ONI) Wasteland 31 (c2c).cbr"
echo.>comics_to_rename/"01-04-12 (IMG) Mudman 02.cbr"
echo.>comics_to_rename/"01-25-12 (DYN) Jennifer Blood 08 (2c).cbr"
echo.>comics_to_rename/"03-07-12 (DYN) Jennifer Blood 10 (2c).cbr"
echo.>comics_to_rename/"03-07-12 (IMG) Fatale 03 (c2c).cbz"
echo.>comics_to_rename/"03-07-12 Sweet Tooth 31.cbz"
echo.>comics_to_rename/"issue.026.cbr"
echo.>comics_to_rename/"'68 Scars 01 (of 04) (2012) (digital-Empire).cbr"
echo.>comics_to_rename/"Adventure Time 003 (2012) (4 covers) (digital-TheGroup).cbr"
echo.>comics_to_rename/"Alabaster Wolves 01 (of 05) (2012) (Digital) (Roxrite-Empire).cbr"
echo.>comics_to_rename/"Amazing Spider-Man - Hookey 001 (2012) (digital-TheGroup).cbr"
echo.>comics_to_rename/"America's Got Powers 01 (of 06) (2012) (Digital) (Fawkes-Empire).cbr"
echo.>comics_to_rename/"American Vampire 025 (2012) (Minutemen-ThosTew).cbz"
echo.>comics_to_rename/"Avengers Assemble 002 (2012) (digital-TheGroup).cbr"
echo.>comics_to_rename/"Avengers Icons - The Vision 001 (2002) (c2c) (ArtNet-DCP).cbz"
echo.>comics_to_rename/"Avengers Icons - The Vision 001 (2002) (noads) (ArtNet-DCP).cbz"
echo.>comics_to_rename/"Avengers Icons - The Vision 002 (2002) (c2c) (ArtNet-DCP).cbz"
echo.>comics_to_rename/"Avengers Icons - The Vision 002 (2002) (noads) (ArtNet-DCP).cbz"
echo.>comics_to_rename/"Avengers Icons - The Vision 003 (2002) (c2c) (ArtNet-DCP).cbz"
echo.>comics_to_rename/"Avengers Icons - The Vision 003 (2002) (noads) (ArtNet-DCP).cbz"
echo.>comics_to_rename/"Avengers Icons - The Vision 004 (2002) (c2c) (ArtNet-DCP).cbz"
echo.>comics_to_rename/"Avengers Icons - The Vision 004 (2002) (noads) (ArtNet-DCP).cbz"
echo.>comics_to_rename/"Avengers VS X-Men 01 (2012) (10 Covers) (Tarutaru-DCP).cbr"
echo.>comics_to_rename/"Avengers Vs X-Men 01 (2012) (1280px+100 Pages) (f) (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"Avengers vs. X-Men Infinite 001 (2012) (f) (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"Avenging Spider-Man 006 (2012) (digital-TheGroup).cbr"
echo.>comics_to_rename/"Batgirl 008 (2012) (Digital) (Roxrite-Empire).cbr"
echo.>comics_to_rename/"Batman Beyond 005 (2012) (Digital First) (ZOOM-Empire).cbz"
echo.>comics_to_rename/"Batman and Robin 008 (2012) (RiZZ3N-Empire).cbr"
echo.>comics_to_rename/"Batman and Robin 08 (2012) (Minutemen-DTermined).cbr"
echo.>comics_to_rename/"Batwoman 08 (2012) (two covers) (Minutemen DTs).cbz"
echo.>comics_to_rename/"Batwoman 08 (2012) (two covers) (Minutemen-DTs).cbz"
echo.>comics_to_rename/"Bionic Woman 001 (2012) (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"Buffy the Vampire Slayer Season 9 09 (2012) (two covers) (Minutemen-DTs).cbz"
echo.>comics_to_rename/"Carnage USA 05 (of 05) (2012) (digital-TheGroup).cbr"
echo.>comics_to_rename/"Chimichanga (2009) (Digital) (G85-Empire).cbr"
echo.>comics_to_rename/"Conan the Barbarian 03 (2012) (two covers) (Minutemen-DTs).cbz"
echo.>comics_to_rename/"Danger Girl - Revolver 03 (of 04) (2012) (2 covers) (digital-Empire).cbr"
echo.>comics_to_rename/"Daredevil - Season One (2012) (digital-Empire).cbr"
echo.>comics_to_rename/"Dark Matter 04 (of 04) (2012) (Digital) (G85-Empire).cbr"
echo.>comics_to_rename/"Dark Matter 04 (of 04) (2012) (Minutemen-DTs).cbz"
echo.>comics_to_rename/"Deadpool 054 (2012) (digital-TheGroup).cbr"
echo.>comics_to_rename/"Deathstroke 08 (2012) (Minutemen-DTs).cbz"
echo.>comics_to_rename/"Demon Knights 008 (2012) (Digital) (Ozy-Empire).cbz"
echo.>comics_to_rename/"Fantastic Four 605 (2012) (Megan-Empire).cbr"
echo.>comics_to_rename/"Fantastic Four 605 (2012) (two covers) (Minutemen-DTs).cbz"
echo.>comics_to_rename/"Formic Wars - Silent Strike 005 (2012) (digital-TheGroup).cbr"
echo.>comics_to_rename/"Frankenstein Agent of S.H.A.D.E. 008 (2012) (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"Frankenstein, Agent of S.H.A.D.E. 08 (2012) (Minutemen-ThosTew).cbz"
echo.>comics_to_rename/"G.I. Joe vol2 012 (2012) (RI cover) (CookieMonster-DCP).cbr"
echo.>comics_to_rename/"Glory 025 (2012) (digital) (Cypher-Empire).cbr"
echo.>comics_to_rename/"Green Lantern - The Animated Series 001 (2012) (Digital) (Razer-Empire).cbz"
echo.>comics_to_rename/"Green Lantern 008 (2012) (Four Covers) (Digital) (Razer-Empire).cbz"
echo.>comics_to_rename/"Green Lantern v5 08 (2012) (c2c) (The Last Kryptonian-DCP).cbr"
echo.>comics_to_rename/"Grifter 08 (2012) (Minutemen-DTs).cbz"
echo.>comics_to_rename/"Grimm Fairy Tales Alice In Wonderland 4(c2c)(2 covers)(2012)(Re-em-DCP).cbr"
echo.>comics_to_rename/"Haunt 23 (2012) (Digital) (Danger-Empire).cbr"
echo.>comics_to_rename/"Infestation 2 - 02 (of 2) (2012) (2 covers) (Digital-Nahga).cbr"
echo.>comics_to_rename/"Journey Into Mystery 636 (2012) (Minutemen-DTs).cbz"
echo.>comics_to_rename/"Legion Lost 08 (2012) (Digital) (G85-Empire).cbr"
echo.>comics_to_rename/"Lobster Johnson - The Burning Hand 04 (of 05) (2012) (digital-Empire).cbr"
echo.>comics_to_rename/"Lobster Johnson - The Burning Hand 04 (of 05) (2012) (two covers) (Minutemen-DTs).cbz"
echo.>comics_to_rename/"Lord of the Jungle 003 (2012) (2 covers) (Digital) (Fawkes-Empire).cbr"
echo.>comics_to_rename/"Marvel Universe Avengers Earth's Mightiest Heroes 001 (2012) (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"Mike Nortons Battlepug v1 - Blood and Drool (2011-2012) (battlepug.com).cbr"
echo.>comics_to_rename/"Mister Terrific 008 (2012) (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"New Avengers 024 (2012) (digital-TheGroup).cbr"
echo.>comics_to_rename/"Orchid 06 (2012) (Minutemen-DTs).cbz"
echo.>comics_to_rename/"Peter Panzerfaust 03 (2012 (Digital) (Danger-Empire).cbr"
echo.>comics_to_rename/"Resurrection Man 008 (2012) (digital-Empire).cbr"
echo.>comics_to_rename/"Rich Johnson's Iron Muslim 001 (2012) (digital-Empire).cbr"
echo.>comics_to_rename/"Rogue v2 (Icons) (2001) 01 (of 04) (Minutemen-Syl3ntBob).cbz"
echo.>comics_to_rename/"Rogue v2 (Icons) (2001) 02 (of 04) (Minutemen-Syl3ntBob).cbz"
echo.>comics_to_rename/"Rogue v2 (Icons) (2001) 03 (of 04) (Minutemen-Syl3ntBob).cbz"
echo.>comics_to_rename/"Rogue v2 (Icons) (2001) 04 (of 04) (Minutemen-Syl3ntBob).cbz"
echo.>comics_to_rename/"Saga 002 (2012) (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"Saucer Country 002 (2012) (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"Scarlet Spider 004 (2012) (Digital) (ZOOM-Empire).cbz"
echo.>comics_to_rename/"Scarlet Spider 004 (2012) (digital-TheGroup).cbr"
echo.>comics_to_rename/"Secret 001 (2012) (Digital) (Fawkes-Empire).cbr"
echo.>comics_to_rename/"Secret Avengers 025 (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"Smoke and Mirrors 02 (of 05) (2012) (2 covers) (digital-Empire).cbr"
echo.>comics_to_rename/"Steampunk Sketchbook 1(c2c)(2012)(Re-em-DCP).cbr"
echo.>comics_to_rename/"Suicide Squad 008 (2012) (Digital) (Roxrite-Empire).cbr"
echo.>comics_to_rename/"Superboy v5 08 (2012) (c2c) (The Last Kryptonian-DCP).cbr"
echo.>comics_to_rename/"The Bionic Man 008 (2 Covers) (2012) (Zone-Empire).cbr"
echo.>comics_to_rename/"The Coming of The Avengers 001 (2012) (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"The Mighty Thor 012.1 (2012) (digital-TheGroup).cbr"
echo.>comics_to_rename/"The Shade 07 (of 12) (2012) (2 covers) (digital-Empire).cbr"
echo.>comics_to_rename/"The Shade 07 (of 12) (2012) (Minutemen-DTermined).cbr"
echo.>comics_to_rename/"The Theater 5(c2c)(2 covers)(2012)(Re-em-DCP).cbr"
echo.>comics_to_rename/"Thief of Thieves 003 (2012) (Digital) (Roxrite-Empire).cbr"
echo.>comics_to_rename/"True Blood - French Quarter 06 (of 6) (2012) (4 covers) (digital) (HomeBrew).cbr"
echo.>comics_to_rename/"Ultimate Comics X-Men 010 (2012) (Megan-Empire).cbr"
echo.>comics_to_rename/"Ultimate Comics X-Men 010 (2012) (ProletariatSax-DCP&Minutemen).cbr"
echo.>comics_to_rename/"Uncanny X-Men 010 (2012) (Megan-Empire).cbr"
echo.>comics_to_rename/"Vampirella Vs. Dracula 3(c2c)(2012)(Re-em-DCP).cbr"
echo.>comics_to_rename/"Vampirella vs. Dracula 003 (2012) (digital-Empire).cbr"
echo.>comics_to_rename/"Wasteland 036 (2012) (Digital) (Zone-Empire).cbr"
echo.>comics_to_rename/"Winter Soldier 004 (2012) (Megan-Empire).cbr"
echo.>comics_to_rename/"Wolverine 304 (2012) (digital-TheGroup).cbr"